### ISSUE TITLE
Dokumentation

### ISSUE THREAD

**Issue by pschwede** [phipse/NittaSeite#1]
Welche ruby gems braucht man zum Beispiel?

``` plain
$ jekyll serve
/usr/lib/ruby/vendor_ruby/jekyll/converters/sass.rb:6:in `<module:Converters>': uninitialized constant Jekyll::Converters::Scss (NameError)
    from /usr/lib/ruby/vendor_ruby/jekyll/converters/sass.rb:5:in `<module:Jekyll>'
    from /usr/lib/ruby/vendor_ruby/jekyll/converters/sass.rb:4:in `<top (required)>'
    from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/lib/ruby/vendor_ruby/jekyll.rb:11:in `block in require_all'
    from /usr/lib/ruby/vendor_ruby/jekyll.rb:10:in `each'
    from /usr/lib/ruby/vendor_ruby/jekyll.rb:10:in `require_all'
    from /usr/lib/ruby/vendor_ruby/jekyll.rb:64:in `<top (required)>'
    from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/bin/jekyll:6:in `<main>'
```

**Comment by uwedd** [comment]
Aha wir nehmen jetzt doch Ruby?

na macht mal ...

**Comment by pschwede** [comment]
War was anderes geplant?

**Comment by uwedd** [comment]
Ähm ja. Wir hatten uns ja nicht umsonst zusammen gesetzt aber mir isses letztenendes egal. :)

**Comment by phipse** [comment]
Ich glaube hier liegt ein Missverständniss vor. jekyll unser static site generator ist in ruby geschrieben; die Seite besteht aus Css3 und HTML5.

[Linux]
Um das ganze auf der Kommandozeile zu bauen, braucht ihr ruby und gem, dann das repo aus-checken, in den gh_pages branch wechseln und 'bundle install' aufrufen. 

Wenn dann alles installiert ist solltet ihr mit:
bundle exec jekyll serve
einen lokal laufenden Server bekommen, der euch IP:Port anzeigt. (bei mir: 0.0.0.0:4000)

https://help.github.com/articles/using-jekyll-with-pages/

**Comment by uwedd** [comment]
Ahh na dann ist ja alles beim Alten. Wir machen es also nicht in oder
mit Ruby sondern wie besprochen mit dem Site Generator.

OSS

Am 05.02.2015 15:21 schrieb phipse: 

> Ich glaube hier liegt ein Missverständniss vor. jekyll unser static site generator ist in ruby geschrieben; die Seite besteht aus Css3 und HTML5. 
> 
> [Linux]
> Um das ganze auf der Kommandozeile zu bauen, braucht ihr ruby und gem, dann das repo aus-checken, in den gh_pages branch wechseln und 'bundle install' aufrufen. 
> 
> Wenn dann alles installiert ist solltet ihr mit:
> bundle exec jekyll serve
> einen lokal laufenden Server bekommen, der euch IP:Port anzeigt. (bei mir: 0.0.0.0:4000) 
> 
> https://help.github.com/articles/using-jekyll-with-pages/ [1] 
> 
> ## 
> 
> Reply to this email directly or view it on GitHub [2].

## Links:

[1] https://help.github.com/articles/using-jekyll-with-pages/
[2] https://github.com/phipse/NittaSeite/issues/1#issuecomment-73053027

**Comment by pschwede** [comment]
Der Site Generator ist in Ruby ;)
Aber wir ändern an ihm nichts.
